name: Release lazysqlite

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          # The token is automatically provided, but now has permission
          generate_release_notes: true

  build-and-upload-assets:
    name: Build and Upload Assets
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Package binary for release
        id: package
        shell: bash
        run: |
          BINARY_NAME="lazysqlite"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            SOURCE_PATH="target/${{ matrix.target }}/release/${BINARY_NAME}.exe"
            ASSET_NAME="${BINARY_NAME}-${{ matrix.target }}.zip"
            7z a $ASSET_NAME ./$SOURCE_PATH
          else
            SOURCE_PATH="target/${{ matrix.target }}/release/${BINARY_NAME}"
            ASSET_NAME="${BINARY_NAME}-${{ matrix.target }}.tar.gz"
            tar -czvf $ASSET_NAME -C $(dirname $SOURCE_PATH) $(basename $SOURCE_PATH)
          fi
          echo "asset_name=${ASSET_NAME}" >> "$GITHUB_OUTPUT"

      # NOTE: actions/upload-release-asset is deprecated.
      # It is better to use softprops/action-gh-release here as well.
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.asset_name }}